# Generated by Django 6.1.1 on 2026-09-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_poll_choice_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
