# Generated by Django 6.1.1 on 2026-10-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll_object', 'owner_object')},
        ),
    ]
